database:
  connections: 3
  database: duawcbov
  host: peanut.db.elephantsql.com
  port: 5432
  pass: XrvC9dK9aTzR0i54u_icQaR2GO6_Y-ve
  user: duawcbov
document:
  collection: BeeHappyTraces
  database: BeeHappyDatabase
  datasource: BeeHappyCluster
  host: mongodb+srv://beehappy:beehappy@beehappycluster.ykz3xfn.mongodb.net/?retryWrites=true&w=majority
scheduler:
  awake:
    cron: 0 0,10,20,30,40,50 * * * *
    #cron: 0 */1 * * * *
    host: https://beehappy.ee/system/awake
    #host: http://127.0.0.1:8080/system/awake
  indicators:
    cron: 0 0 0,6,12,18 * * *
    #cron: 0 */1 * * * *
    dollar: https://api.cmfchile.cl/api-sbifv3/recursos_api/dolar/
    euro: https://api.cmfchile.cl/api-sbifv3/recursos_api/euro/
    foment_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/uf/
    monthly_tax_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/utm/
    token: 8868f4356814969f5c63d9dc122e95bb12b10e61
server:
  port: 8080
system:
  version: 2.101122